import { AlertTriangle, CheckCircle2, LoaderCircle, Server } from "lucide-react";
import type { RefObject } from "react";
import type { ZeusSnapshot, ZeusTransferPreview, ZeusTransferResult } from "../../api/clients/zeus";
import { ReviewEffects } from "../shared/ReviewEffects";
import type { TransferUiState } from "./controllers/useTransferController";

const bytes = (value: number) => new Intl.NumberFormat("en", { style: "unit", unit: value >= 1_000_000 ? "megabyte" : "kilobyte", unitDisplay: "short", maximumFractionDigits: 1 }).format(value / (value >= 1_000_000 ? 1_000_000 : 1_000));
export function TransferStage(props: { visible: boolean; snapshot: ZeusSnapshot | null; state: TransferUiState; preview: ZeusTransferPreview | null; result: ZeusTransferResult | null; error: string; buttonRef: RefObject<HTMLButtonElement>; headingRef: RefObject<HTMLHeadingElement>; successRef: RefObject<HTMLDivElement>; errorRef: RefObject<HTMLDivElement>; onConnect: () => void; onPreview: () => void; onConfirm: () => void; onReset: () => void }) {
  if (!props.visible) return null;
  return <section className="section-block" aria-labelledby="prepare-heading"><div className="section-heading"><h2 id="prepare-heading">Prepare campaign on Zeus</h2><p>Review and transfer the exact campaign inputs. The preview checks the destination again and never starts a simulation or submits a job.</p></div>
    {!props.snapshot && <div className="state-panel"><Server aria-hidden="true" /><div><strong>Connect to Zeus first</strong><p>A read-only connection profile is required before the application can inspect the destination.</p><button className="secondary-button compact-action" type="button" onClick={props.onConnect}>Open Zeus connection</button></div></div>}
    {props.snapshot && props.state === "idle" && <div className="prepare-card"><div><strong>Zeus connection profile selected</strong><p>{props.snapshot.profile.username} · {props.snapshot.profile.project_directory}</p><p>The destination, Git commit, working tree, and file hashes will be checked again during review.</p></div><button ref={props.buttonRef} className="secondary-button" type="button" onClick={props.onPreview}>Review Zeus preparation</button></div>}
    {props.state === "previewing" && <div className="state-panel" role="status"><LoaderCircle aria-hidden="true" /><div><strong>Inspecting the Zeus destination</strong><p>No files are being changed.</p></div></div>}
    {props.preview && ["review", "preparing"].includes(props.state) && <div className="transfer-review" aria-busy={props.state === "preparing"}><div className="section-heading"><h3 ref={props.headingRef} tabIndex={-1}>Review preparation</h3><p>Only missing files will be copied. Existing identical files will be reused; any conflicting file blocks preparation.</p></div><dl className="transfer-facts"><div><dt>Destination</dt><dd>{props.preview.destination.campaign_directory}</dd></div><div><dt>Campaign commit</dt><dd><code>{props.preview.campaign.git_commit.slice(0, 12)}</code></dd></div><div><dt>Zeeman ensembles</dt><dd>{props.preview.artifacts.ensemble_count}</dd></div><div><dt>Total artifacts</dt><dd>{props.preview.artifacts.total_count}</dd></div><div><dt>Missing — will copy</dt><dd>{props.preview.artifacts.missing_count} · {bytes(props.preview.artifacts.missing_bytes)}</dd></div><div><dt>Already identical — will reuse</dt><dd>{props.preview.artifacts.identical_count}</dd></div><div><dt>Total validated size</dt><dd>{bytes(props.preview.artifacts.total_bytes)}</dd></div></dl><ReviewEffects effects={[<>Existing files will never be overwritten.</>, <>No simulation will start.</>, <>No Zeus job will be submitted.</>]} /><div className="form-actions"><button className="text-button" type="button" disabled={props.state === "preparing"} onClick={props.onReset}>Cancel</button><button className="primary-button" type="button" disabled={props.state === "preparing"} onClick={props.onConfirm}>{props.state === "preparing" ? <><LoaderCircle aria-hidden="true" /> Preparing…</> : "Prepare campaign on Zeus"}</button></div></div>}
    {props.state === "success" && props.result && <div ref={props.successRef} className="connection-panel connection-panel--connected" role="status" tabIndex={-1}><CheckCircle2 aria-hidden="true" /><div><strong>Campaign prepared on Zeus</strong><p>{props.result.transferred_count} files copied; {props.result.reused_identical_count} identical files reused.</p><p>No simulation was started and no Zeus job was submitted.</p></div></div>}
    {props.error && <div ref={props.errorRef} className="state-panel state-panel--error" role="alert" tabIndex={-1}><AlertTriangle aria-hidden="true" /><div><strong>Zeus preparation stopped safely</strong><p>{props.error}</p></div></div>}
  </section>;
}
