"""Explicit, at-most-once submission of one prepared 2D smoke PBS.

The public boundary accepts a campaign id and a Zeus profile, never a command,
job path, host, or scheduler option.  Preview is read-only.  Confirmation uses
a fixed remote receiver which revalidates the complete prepared campaign under
a remote lock before invoking the fixed qsub executable once.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import secrets
import shlex
import stat as stat_module
import subprocess
import threading
import time
from dataclasses import dataclass, replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Mapping, Protocol

from workflow_api.discovery import build_registry
from workflow_api.mot_2d_plan import render_campaign_files
from workflow_api.preview_registry import PreviewRegistry
from workflow_api.zeus_snapshot import ZEUS_HOST, ZeusProfile
from workflow_api.zeus_transfer import (
    COMMIT_RE,
    TOKEN_LIFETIME_SECONDS,
    MAX_PENDING_PREVIEWS,
    CampaignArtifactPlanner,
    ZeusPreparationError,
    _load_manifest,
)

QSUB = "/usr/local/bin/qsub"
NONCE_RE = re.compile(r"^[0-9a-f]{32}$")
KEY_RE = re.compile(r"^[0-9a-f]{64}$")
JOB_PARENT_RE = re.compile(r"^[0-9]+(?:\[\])?\.zeus-master$")
MAX_REMOTE_OUTPUT = 64 * 1024
SAFE_UNTRACKED_ROOTS = frozenset({"data", "graphs"})
SAFE_UNTRACKED_SUFFIXES = frozenset({".json", ".npy", ".csv", ".db", ".sqlite", ".png", ".pdf", ".pbs", ".out", ".err", ".txt"})


class ZeusSubmissionError(RuntimeError):
    """Stable, sanitized error code for the HTTP adapter."""

    def __init__(self, code: str):
        super().__init__(code)
        self.code = code


@dataclass(frozen=True)
class RepositoryRevision:
    commit: str
    clean: bool


class RepositoryRevisionService:
    """Read and validate the local Git revision without changing the checkout."""

    def __init__(self, repository_root: Path, git_executable: Path):
        self.root = repository_root.resolve(strict=True)
        self.git = git_executable.resolve(strict=True)

    @staticmethod
    def _safe_untracked_status(root: Path, raw: bytes) -> bool:
        try:
            for record in raw.split(b"\0"):
                if not record: continue
                if len(record)<4 or record[:2]!=b"??" or record[2:3]!=b" ": return False
                text=record[3:].decode("utf-8","strict");pure=Path(text)
                if pure.is_absolute() or pure.as_posix()!=text or any(part in {"",".",".."} for part in pure.parts): return False
                if not pure.parts or pure.parts[0] not in SAFE_UNTRACKED_ROOTS or pure.suffix.lower() not in SAFE_UNTRACKED_SUFFIXES: return False
                if not stat_module.S_ISREG((root/pure).lstat().st_mode): return False
            return True
        except (OSError,UnicodeError): return False

    def inspect(self) -> RepositoryRevision:
        env={"PATH":str(self.git.parent),"HOME":str(Path.home()),"LC_ALL":"C","GIT_CONFIG_NOSYSTEM":"1","GIT_OPTIONAL_LOCKS":"0","GIT_TERMINAL_PROMPT":"0"}
        def run(args: list[str]) -> bytes:
            try: result=subprocess.run([str(self.git),*args],cwd=self.root,env=env,stdin=subprocess.DEVNULL,stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=False,close_fds=True,timeout=10,check=False)
            except subprocess.TimeoutExpired: raise ZeusSubmissionError("local_repository_unavailable") from None
            if result.returncode or len(result.stdout)>1024*1024 or len(result.stderr)>65536: raise ZeusSubmissionError("local_repository_unavailable")
            return result.stdout
        try:
            commit=run(["rev-parse","--verify","HEAD^{commit}"]).decode("ascii").strip()
            status=run(["status","--porcelain=v1","-z","--untracked-files=all"])
        except UnicodeError: raise ZeusSubmissionError("local_repository_unavailable") from None
        if not COMMIT_RE.fullmatch(commit): raise ZeusSubmissionError("local_repository_unavailable")
        return RepositoryRevision(commit, self._safe_untracked_status(self.root, status))


@dataclass(frozen=True)
class SubmissionRemoteState:
    status: str
    job_id: str | None = None
    nonce: str | None = None
    branch: str | None = None
    submitted_unix_s: int | None = None


class SmokeSubmissionTransport(Protocol):
    def inspect(
        self, *, files: Mapping[str, str], campaign: str, job_file: str,
        commit: str, submission_key: str,
    ) -> SubmissionRemoteState: ...

    def submit(
        self, *, files: Mapping[str, str], campaign: str, job_file: str,
        commit: str, submission_key: str, nonce: str,
    ) -> SubmissionRemoteState: ...


# The receiver has two operations only.  All paths and hashes are generated by
# the local service and validated again remotely; callers cannot supply argv.
_REMOTE_SCRIPT = r'''import hashlib,json,os,pathlib,re,stat,subprocess,sys,tempfile,time
op,username,project_text,encoded= sys.argv[1:5]
try: request=json.loads(__import__('base64').urlsafe_b64decode(encoded).decode('utf-8'))
except Exception: print(json.dumps({'error':'invalid_request'})); raise SystemExit(20)
expected_keys={'files','campaign','job_file','commit','submission_key','nonce'}
if not isinstance(request,dict) or set(request)!=expected_keys: print(json.dumps({'error':'invalid_request'})); raise SystemExit(20)
files=request['files']; campaign=request['campaign']; job_file=request['job_file']; commit=request['commit']; key=request['submission_key']; nonce=request['nonce']
hex40=re.compile(r'^[0-9a-f]{40}$'); hex64=re.compile(r'^[0-9a-f]{64}$'); hex32=re.compile(r'^[0-9a-f]{32}$')
def rel(text,prefix):
    if not isinstance(text,str) or not text or len(text.encode())>512 or '\\' in text or not text.isprintable(): raise ValueError()
    pure=pathlib.PurePosixPath(text)
    if pure.is_absolute() or pure.as_posix()!=text or any(x in ('','.','..') for x in pure.parts) or pure.parts[:len(prefix)]!=prefix: raise ValueError()
    return pure
try:
    campaign_pure=rel(campaign,('data','optimization','mot_2d'))
    if len(campaign_pure.parts)!=4: raise ValueError()
    job_pure=rel(job_file,campaign_pure.parts)
    if job_pure.parts[len(campaign_pure.parts):] != ('jobs','01_smoke.pbs'): raise ValueError()
    if not isinstance(files,dict) or len(files)!=72 or any(not isinstance(k,str) or not isinstance(v,str) or not hex64.fullmatch(v) for k,v in files.items()): raise ValueError()
    paths={rel(k,('data',)):v for k,v in files.items()}
    if job_pure not in paths or not hex40.fullmatch(str(commit)) or not hex64.fullmatch(str(key)): raise ValueError()
    if nonce is not None and (not isinstance(nonce,str) or not hex32.fullmatch(nonce)): raise ValueError()
    if op=='submit' and nonce is None: raise ValueError()
except ValueError: print(json.dumps({'error':'invalid_request'})); raise SystemExit(20)
project=pathlib.Path(project_text); home=pathlib.Path('/home')/username
try: project=project.resolve(strict=True)
except (OSError,RuntimeError): print(json.dumps({'error':'remote_project_missing'})); raise SystemExit(21)
if not project.is_dir() or (project!=home and home not in project.parents): print(json.dumps({'error':'remote_project_missing'})); raise SystemExit(21)
NOFOLLOW=getattr(os,'O_NOFOLLOW',0); DIRECTORY=getattr(os,'O_DIRECTORY',0)
try: root_fd=os.open(project,os.O_RDONLY|DIRECTORY|NOFOLLOW)
except OSError: print(json.dumps({'error':'remote_project_missing'})); raise SystemExit(21)
def safe_target(pure):
    current=project
    for part in pure.parts:
        current=current/part
        if current.is_symlink(): raise ValueError()
    return current
try: targets={pure:safe_target(pure) for pure in paths}; campaign_path=safe_target(campaign_pure)
except (OSError,ValueError): print(json.dumps({'error':'remote_preparation_invalid'})); raise SystemExit(22)
def run(argv,timeout=15,input_data=None):
    return subprocess.run(argv,cwd=project,input=input_data,stdin=subprocess.DEVNULL if input_data is None else None,stdout=subprocess.PIPE,stderr=subprocess.PIPE,
      env={'PATH':'/usr/local/bin:/opt/pbs/bin:/usr/bin:/bin','HOME':str(home),'LC_ALL':'C'},timeout=timeout,check=False,shell=False,close_fds=True)
def safe_worktree_status(raw):
    safe_suffixes={'.json','.npy','.csv','.db','.sqlite','.png','.pdf','.pbs','.out','.err','.txt'}
    try:
        for record in raw.split(b'\0'):
            if not record: continue
            if len(record)<4 or record[:2]!=b'??' or record[2:3]!=b' ': return False
            text=record[3:].decode('utf-8','strict'); pure=pathlib.PurePosixPath(text)
            if pure.is_absolute() or pure.as_posix()!=text or any(part in ('','.','..') for part in pure.parts): return False
            if not pure.parts or pure.parts[0] not in {'data','graphs'} or pure.suffix.lower() not in safe_suffixes: return False
            if not stat.S_ISREG((project.joinpath(*pure.parts)).lstat().st_mode): return False
        return True
    except Exception: return False
def validate_all():
    try:
        head=run(['/usr/bin/git','rev-parse','--verify','HEAD^{commit}']); dirty=run(['/usr/bin/git','status','--porcelain=v1','-z','--untracked-files=all'])
        branch=run(['/usr/bin/git','branch','--show-current'])
        if head.returncode or dirty.returncode or branch.returncode or head.stdout.decode('ascii').strip()!=commit or not safe_worktree_status(dirty.stdout): return None
        branch_text=branch.stdout.decode('utf-8','strict').strip()
        if not branch_text or len(branch_text)>256 or not branch_text.isprintable(): return None
        for pure,digest in paths.items():
            target=targets[pure]
            metadata=target.lstat()
            if not stat.S_ISREG(metadata.st_mode): return None
            observed=hashlib.sha256()
            with target.open('rb') as stream:
                for chunk in iter(lambda:stream.read(1048576),b''): observed.update(chunk)
            if observed.hexdigest()!=digest: return None
        return branch_text
    except Exception: return None
def open_child_directory(parent_fd,name,create=False):
    if create:
        try: os.mkdir(name,0o700,dir_fd=parent_fd)
        except FileExistsError: pass
    return os.open(name,os.O_RDONLY|DIRECTORY|NOFOLLOW,dir_fd=parent_fd)
def records_directory(create=False):
    campaign_fd=os.open(campaign_path,os.O_RDONLY|DIRECTORY|NOFOLLOW)
    try:
        workflow_fd=open_child_directory(campaign_fd,'.workflow',create)
        try: return open_child_directory(workflow_fd,'submissions',create)
        finally: os.close(workflow_fd)
    finally: os.close(campaign_fd)
def read_record(records_fd,name):
    if records_fd is None: return None
    try:
        fd=os.open(name,os.O_RDONLY|NOFOLLOW,dir_fd=records_fd)
        metadata=os.fstat(fd)
        if not stat.S_ISREG(metadata.st_mode) or metadata.st_size>16384: os.close(fd); raise ValueError()
        with os.fdopen(fd,'r',encoding='utf-8') as source: value=json.load(source)
        if not isinstance(value,dict) or value.get('submission_key')!=key: raise ValueError()
        return value
    except FileNotFoundError: return None
    except Exception: raise ValueError()
def state(records_fd):
    final=read_record(records_fd,'smoke.json'); unresolved=read_record(records_fd,'smoke.pending.json')
    if final is not None:
        jid=final.get('job_id'); saved_nonce=final.get('nonce')
        expected_id=r'^\d+\[\]\.zeus-master$' if b'#PBS -J ' in targets[job_pure].read_bytes() else r'^\d+\.zeus-master$'
        if final.get('job_file')!=job_file or final.get('commit')!=commit or not isinstance(jid,str) or not re.fullmatch(expected_id,jid) or not isinstance(saved_nonce,str) or not hex32.fullmatch(saved_nonce): raise ValueError()
        completed=final.get('completed_unix_s')
        if not isinstance(completed,int) or completed<0: raise ValueError()
        return {'status':'submitted','job_id':jid,'nonce':saved_nonce,'submitted_unix_s':completed}
    if unresolved is not None:
        saved_nonce=unresolved.get('nonce')
        if unresolved.get('job_file')!=job_file or unresolved.get('commit')!=commit or not isinstance(saved_nonce,str) or not hex32.fullmatch(saved_nonce): raise ValueError()
        return {'status':'ambiguous','nonce':saved_nonce}
    return {'status':'eligible'}
def smoke_started():
    try: (campaign_path/'smoke').lstat(); return True
    except FileNotFoundError: return False
if op=='inspect':
    branch=validate_all()
    if branch is None: print(json.dumps({'error':'remote_preparation_invalid'})); raise SystemExit(22)
    try:
        try: records_fd=records_directory(False)
        except FileNotFoundError: records_fd=None
        if records_fd is not None:
            try: os.stat('smoke.lock',dir_fd=records_fd,follow_symlinks=False); print(json.dumps({'error':'submission_busy'})); raise SystemExit(24)
            except FileNotFoundError: pass
        current=state(records_fd)
        if current['status']!='submitted' and smoke_started(): print(json.dumps({'error':'smoke_already_started'})); raise SystemExit(26)
        current['branch']=branch; print(json.dumps(current,sort_keys=True))
        if records_fd is not None: os.close(records_fd)
    except (OSError,ValueError): print(json.dumps({'error':'submission_record_invalid'})); raise SystemExit(23)
    raise SystemExit()
if op!='submit': print(json.dumps({'error':'invalid_request'})); raise SystemExit(20)
try:
    records_fd=records_directory(True)
    os.mkdir('smoke.lock',0o700,dir_fd=records_fd)
except FileExistsError: print(json.dumps({'error':'submission_busy'})); raise SystemExit(24)
except OSError: print(json.dumps({'error':'submission_record_invalid'})); raise SystemExit(23)
try:
    if validate_all() is None: print(json.dumps({'error':'remote_preparation_invalid'})); raise SystemExit(22)
    current=state(records_fd)
    if current['status']=='submitted': print(json.dumps(current,sort_keys=True)); raise SystemExit()
    if current['status']=='ambiguous': print(json.dumps({'error':'submission_ambiguous'})); raise SystemExit(25)
    if smoke_started(): print(json.dumps({'error':'smoke_already_started'})); raise SystemExit(26)
    pending_payload={'version':1,'submission_key':key,'nonce':nonce,'job_file':job_file,'commit':commit,'created_unix_s':int(time.time())}
    fd=os.open('smoke.pending.json',os.O_WRONLY|os.O_CREAT|os.O_EXCL|NOFOLLOW,0o600,dir_fd=records_fd)
    with os.fdopen(fd,'w',encoding='utf-8') as output:
        json.dump(pending_payload,output,sort_keys=True); output.write('\n'); output.flush(); os.fsync(output.fileno())
    os.fsync(records_fd)
    # Submit the verified bytes through stdin.  qsub never reopens a path which
    # another process could swap after validate_all() returned.
    try:
        job_bytes=targets[job_pure].read_bytes()
        if hashlib.sha256(job_bytes).hexdigest()!=paths[job_pure]: raise RuntimeError()
        result=run(['/usr/local/bin/qsub','-v','MOT_UI_SUBMISSION_ID='+nonce],30,job_bytes)
    except Exception: print(json.dumps({'error':'submission_ambiguous'})); raise SystemExit(25)
    try: raw_stdout=result.stdout.decode('ascii','strict'); stderr=result.stderr.decode('utf-8','replace')
    except Exception: print(json.dumps({'error':'submission_ambiguous'})); raise SystemExit(25)
    expected_id=r'\d+\[\]\.zeus-master' if b'#PBS -J ' in job_bytes else r'\d+\.zeus-master'
    if result.returncode!=0 or len(raw_stdout)>256 or stderr or not re.fullmatch(expected_id+r'\n?',raw_stdout):
        print(json.dumps({'error':'submission_ambiguous'})); raise SystemExit(25)
    stdout=raw_stdout[:-1] if raw_stdout.endswith('\n') else raw_stdout
    receipt={**pending_payload,'status':'submitted','job_id':stdout,'completed_unix_s':int(time.time())}
    temporary='.smoke-'+nonce+'.tmp'
    fd=os.open(temporary,os.O_WRONLY|os.O_CREAT|os.O_EXCL|NOFOLLOW,0o600,dir_fd=records_fd)
    with os.fdopen(fd,'w',encoding='utf-8') as output:
        json.dump(receipt,output,sort_keys=True); output.write('\n'); output.flush(); os.fsync(output.fileno())
    try: os.link(temporary,'smoke.json',src_dir_fd=records_fd,dst_dir_fd=records_fd,follow_symlinks=False)
    except FileExistsError:
        existing=state(records_fd)
        if existing.get('job_id')!=stdout: print(json.dumps({'error':'submission_record_invalid'})); raise SystemExit(23)
    finally:
        try: os.unlink(temporary,dir_fd=records_fd)
        except FileNotFoundError: pass
    os.unlink('smoke.pending.json',dir_fd=records_fd); os.fsync(records_fd)
    print(json.dumps({'status':'submitted','job_id':stdout,'nonce':nonce,'submitted_unix_s':receipt['completed_unix_s']},sort_keys=True))
finally:
    try: os.rmdir('smoke.lock',dir_fd=records_fd)
    except OSError: pass
    try: os.close(records_fd)
    except OSError: pass
'''


class PinnedSshSmokeSubmissionTransport:
    """Fixed SSH adapter for the embedded smoke-submission receiver."""

    def __init__(self, repository_root: Path, ssh_executable: Path, profile: ZeusProfile, *, timeout: float = 45):
        self.root = repository_root.resolve(strict=True)
        self.ssh = ssh_executable.resolve(strict=True)
        self.profile = profile
        self.timeout = timeout
        if not self.ssh.is_file() or not os.access(self.ssh, os.X_OK) or self.root in self.ssh.parents:
            raise ValueError("The trusted SSH executable is unavailable.")

    def _request(self, operation: str, **payload: object) -> SubmissionRemoteState:
        if operation not in {"inspect", "submit"}:
            raise ZeusSubmissionError("remote_response_invalid")
        integrity_code = "submission_outcome_unknown" if operation == "submit" else "remote_response_invalid"
        encoded = base64.urlsafe_b64encode(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()).decode("ascii")
        script = base64.urlsafe_b64encode(_REMOTE_SCRIPT.encode()).decode("ascii")
        wrapper = "import base64,sys;payload=sys.argv[1];sys.argv=sys.argv[1:];exec(base64.urlsafe_b64decode(payload).decode('utf-8'))"
        remote = shlex.join(("python3", "-c", wrapper, script, operation, self.profile.username, self.profile.project_directory, encoded))
        argv = [str(self.ssh), "-F", "none", "-T", "-o", "BatchMode=yes", "-o", "PasswordAuthentication=no", "-o", "KbdInteractiveAuthentication=no", "-o", "NumberOfPasswordPrompts=0", "-o", "ConnectTimeout=8", "-o", "ConnectionAttempts=1", "-o", "StrictHostKeyChecking=yes", "-o", "ForwardAgent=no", "-o", "ClearAllForwardings=yes", "-o", "PermitLocalCommand=no", "-o", "ProxyCommand=none", "-o", "ProxyJump=none", "-o", "KnownHostsCommand=none", "-o", "CanonicalizeHostname=no", "-o", "LogLevel=ERROR", f"{self.profile.username}@{ZEUS_HOST}", remote]
        env = {"PATH": str(self.ssh.parent), "HOME": str(Path.home()), "LC_ALL": "C"}
        if os.environ.get("SSH_AUTH_SOCK"): env["SSH_AUTH_SOCK"] = os.environ["SSH_AUTH_SOCK"]
        try:
            result = subprocess.run(argv, cwd=self.root, env=env, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False, close_fds=True, timeout=self.timeout, check=False)
        except subprocess.TimeoutExpired:
            raise ZeusSubmissionError("submission_outcome_unknown" if operation == "submit" else "zeus_timeout") from None
        if len(result.stdout) > MAX_REMOTE_OUTPUT or len(result.stderr) > MAX_REMOTE_OUTPUT:
            raise ZeusSubmissionError(integrity_code)
        stderr = result.stderr.decode("utf-8", "replace").lower()
        if result.returncode and not result.stdout:
            if "host key verification failed" in stderr: raise ZeusSubmissionError("zeus_host_key_untrusted")
            if "permission denied" in stderr: raise ZeusSubmissionError("zeus_authentication_required")
            if "could not resolve hostname" in stderr or "connection refused" in stderr: raise ZeusSubmissionError("zeus_unreachable")
        # Once a submit receiver may have reached qsub, stderr makes the
        # outcome untrustworthy even when stdout resembles a success record.
        if stderr:
            raise ZeusSubmissionError(integrity_code)
        try: response = json.loads(result.stdout.decode("utf-8", "strict"))
        except (UnicodeError, json.JSONDecodeError):
            raise ZeusSubmissionError(integrity_code) from None
        if not isinstance(response, dict): raise ZeusSubmissionError(integrity_code)
        if "error" in response:
            code = response.get("error")
            allowed = {"invalid_request", "remote_project_missing", "remote_preparation_invalid", "submission_record_invalid", "submission_busy", "submission_ambiguous", "smoke_already_started"}
            if operation == "submit" and code in {"submission_ambiguous", "submission_record_invalid"}:
                raise ZeusSubmissionError("submission_outcome_unknown")
            if code not in allowed:
                raise ZeusSubmissionError(integrity_code)
            raise ZeusSubmissionError(str(code))
        if result.returncode != 0:
            raise ZeusSubmissionError(integrity_code)
        status, job_id, nonce = response.get("status"), response.get("job_id"), response.get("nonce")
        if status not in {"eligible", "submitted", "ambiguous"}: raise ZeusSubmissionError(integrity_code)
        expected_keys = {
            ("inspect", "eligible"): {"status", "branch"},
            ("inspect", "ambiguous"): {"status", "nonce", "branch"},
            ("inspect", "submitted"): {"status", "job_id", "nonce", "submitted_unix_s", "branch"},
            ("submit", "submitted"): {"status", "job_id", "nonce", "submitted_unix_s"},
        }.get((operation, status))
        if expected_keys is None or set(response) != expected_keys:
            raise ZeusSubmissionError(integrity_code)
        if status == "submitted" and (not isinstance(job_id, str) or not JOB_PARENT_RE.fullmatch(job_id)):
            raise ZeusSubmissionError(integrity_code)
        if status in {"ambiguous", "submitted"} and (not isinstance(nonce, str) or not NONCE_RE.fullmatch(nonce)):
            raise ZeusSubmissionError(integrity_code)
        branch = response.get("branch")
        if operation == "inspect" and (not isinstance(branch, str) or not branch or len(branch) > 256 or not branch.isprintable()):
            raise ZeusSubmissionError(integrity_code)
        submitted = response.get("submitted_unix_s")
        if status == "submitted" and (not isinstance(submitted, int) or not 0 <= submitted <= 253402300799):
            raise ZeusSubmissionError(integrity_code)
        return SubmissionRemoteState(status, job_id if isinstance(job_id, str) else None, nonce if isinstance(nonce, str) else None, branch if isinstance(branch, str) else None, submitted if isinstance(submitted, int) else None)

    def inspect(self, **kwargs: object) -> SubmissionRemoteState:
        return self._request("inspect", **kwargs, nonce=None)

    def submit(self, **kwargs: object) -> SubmissionRemoteState:
        return self._request("submit", **kwargs)


@dataclass(frozen=True)
class _Pending:
    session_id: str
    campaign_id: str
    campaign_root: Path
    profile: ZeusProfile
    commit: str
    files: Mapping[str, str]
    job_file: str
    submission_key: str
    nonce: str
    expires_at: float
    result: Mapping[str, object] | None = None
    terminal_error: str | None = None


class ZeusSmokeSubmissionCoordinator:
    """HTTP-facing preview/confirm coordinator for exactly one smoke PBS."""

    def __init__(self, repository_root: Path, ssh_executable: Path, git_executable: Path, *, clock=time.time, token_factory=None, transport_factory=None):
        self.root = repository_root.resolve(strict=True); self.ssh = ssh_executable.resolve(strict=True); self.git = git_executable.resolve(strict=True)
        self.clock = clock; self.transport_factory = transport_factory or (lambda profile: PinnedSshSmokeSubmissionTransport(self.root, self.ssh, profile))
        self._previews = PreviewRegistry[_Pending](clock=clock, token_factory=token_factory)
        self._confirm_lock = threading.Lock()
        if not self.git.is_file() or not os.access(self.git,os.X_OK) or self.root in self.git.parents:
            raise ValueError("The trusted Git executable is unavailable.")

    def _revision(self) -> tuple[str, bool]:
        env={"PATH":str(self.git.parent),"HOME":str(Path.home()),"LC_ALL":"C","GIT_CONFIG_NOSYSTEM":"1","GIT_OPTIONAL_LOCKS":"0","GIT_TERMINAL_PROMPT":"0","GIT_PAGER":"cat"}
        def run(args: list[str]) -> bytes:
            try: result=subprocess.run([str(self.git),*args],cwd=self.root,env=env,stdin=subprocess.DEVNULL,stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=False,close_fds=True,timeout=10,check=False)
            except subprocess.TimeoutExpired: raise ZeusSubmissionError("local_repository_unavailable") from None
            if result.returncode or len(result.stdout)>1024*1024 or len(result.stderr)>65536: raise ZeusSubmissionError("local_repository_unavailable")
            return result.stdout
        try:
            commit=run(["rev-parse","--verify","HEAD^{commit}"]).decode("ascii").strip()
            status=run(["status","--porcelain=v1","-z","--untracked-files=all"])
        except UnicodeError: raise ZeusSubmissionError("local_repository_unavailable") from None
        if not COMMIT_RE.fullmatch(commit): raise ZeusSubmissionError("local_repository_unavailable")
        return commit,self._safe_untracked_status(status)

    def _safe_untracked_status(self, raw: bytes) -> bool:
        """Allow generated data only; reject untracked import/native code."""
        return RepositoryRevisionService._safe_untracked_status(self.root, raw)

    def _plan(self, campaign_id: str) -> tuple[Path, dict[str, object], str, dict[str, str], str, str]:
        entry=build_registry(self.root).get(campaign_id)
        if entry is None or entry.family!="mot_2d": raise ZeusSubmissionError("campaign_not_found")
        try: manifest=_load_manifest(entry.manifest)
        except ZeusPreparationError as error: raise ZeusSubmissionError("campaign_not_canonical") from error
        campaign=entry.manifest.parent
        if manifest.get("stage")!="smoke": raise ZeusSubmissionError("campaign_not_smoke")
        try:
            artifact_plan = CampaignArtifactPlanner(self.root).plan(campaign)
            selected, commit = artifact_plan.files, artifact_plan.commit
            canonical=render_campaign_files(manifest, campaign, self.root)
        except (ZeusPreparationError, ValueError, OSError) as error:
            raise ZeusSubmissionError("campaign_not_canonical") from error
        manifest_path=campaign/"campaign.json"; job=campaign/"jobs/01_smoke.pbs"
        if manifest_path.read_bytes()!=canonical["campaign.json"] or job.read_bytes()!=canonical["jobs/01_smoke.pbs"]:
            raise ZeusSubmissionError("campaign_not_canonical")
        files={path:item[1] for path,item in selected.items()}
        campaign_relative=campaign.relative_to(self.root).as_posix(); job_relative=job.relative_to(self.root).as_posix()
        key=hashlib.sha256(json.dumps({"campaign":campaign_relative,"commit":commit,"manifest":files[campaign_relative+"/campaign.json"],"pbs":files[job_relative]},sort_keys=True,separators=(",",":")).encode()).hexdigest()
        return campaign,manifest,commit,files,job_relative,key

    def preview(self, request: Mapping[str, object], *, session_id: str) -> dict[str, object]:
        if set(request)!={"campaign_id","username","project_directory"} or not isinstance(request.get("campaign_id"),str): raise ZeusSubmissionError("request_invalid")
        try: profile=ZeusProfile.parse({"username":request.get("username"),"project_directory":request.get("project_directory")})
        except ValueError as error: raise ZeusSubmissionError("profile_invalid") from error
        campaign_id=str(request["campaign_id"]); campaign,manifest,commit,files,job,key=self._plan(campaign_id)
        local_commit,clean=self._revision()
        if not clean or local_commit!=commit: raise ZeusSubmissionError("local_checkout_mismatch")
        transport=self.transport_factory(profile); state=transport.inspect(files=files,campaign=campaign.relative_to(self.root).as_posix(),job_file=job,commit=commit,submission_key=key)
        if state.branch is None: raise ZeusSubmissionError("remote_response_invalid")
        if state.status=="ambiguous": raise ZeusSubmissionError("submission_outcome_unknown")
        if state.status=="submitted": raise ZeusSubmissionError("already_submitted")
        nonce=secrets.token_hex(16); expires=self.clock()+TOKEN_LIFETIME_SECONDS
        pending=_Pending(session_id,campaign_id,campaign,profile,commit,files,job,key,nonce,expires)
        try:
            token = self._previews.add(
                pending,
                expires_at=expires,
                capacity=MAX_PENDING_PREVIEWS,
            )
        except OverflowError as error:
            raise ZeusSubmissionError("too_many_pending_previews") from error
        name=manifest.get("name") if isinstance(manifest.get("name"),str) else campaign.name
        s0_values=manifest.get("s0_values")
        if not isinstance(s0_values,list) or not s0_values: raise ZeusSubmissionError("campaign_not_canonical")
        return {"preview_token":token,"expires_in_seconds":TOKEN_LIFETIME_SECONDS,"campaign":{"id":campaign_id,"name":name,"path":campaign.relative_to(self.root).as_posix(),"git_commit":commit,"s0_values":s0_values},"stage":{"id":"smoke","label":"Smoke check","purpose":"Validate the prepared 2D-MOT campaign before longer optimization stages."},"job":{"file":"jobs/01_smoke.pbs","kind":"job" if len(s0_values)==1 else "array","task_count":len(s0_values),"queue":"zeus_combined_q","cores_per_task":1,"memory_per_task_bytes":68719476736,"walltime_seconds":1200},"remote":{"host":ZEUS_HOST,"project_directory":profile.project_directory,"commit":commit,"branch":state.branch,"dirty":False},"inputs":{"verified_count":72,"status":"ready"},"effects":{"submit_smoke":True,"submit_later_stages":False,"modify_files":False},"later_stages_locked":True}

    def confirm(self, request: Mapping[str, object], *, session_id: str) -> dict[str, object]:
        if set(request)!={"preview_token"} or not isinstance(request.get("preview_token"),str): raise ZeusSubmissionError("request_invalid")
        token=str(request["preview_token"])
        with self._confirm_lock:
            record = self._previews.get(token)
            pending = record.value if record is not None else None
            if pending is None or not secrets.compare_digest(pending.session_id,session_id): raise ZeusSubmissionError("confirmation_invalid")
            if pending.result is not None: return dict(pending.result)
            if pending.terminal_error is not None: raise ZeusSubmissionError(pending.terminal_error)
            if self.clock()>pending.expires_at:
                self._previews.pop(token)
                raise ZeusSubmissionError("confirmation_expired")
            campaign,_,commit,files,job,key=self._plan(pending.campaign_id); local_commit,clean=self._revision()
            if campaign!=pending.campaign_root or not clean or local_commit!=commit or commit!=pending.commit or files!=pending.files or job!=pending.job_file or key!=pending.submission_key: raise ZeusSubmissionError("local_files_changed")
            transport=self.transport_factory(pending.profile)
            try:
                state=transport.submit(files=files,campaign=campaign.relative_to(self.root).as_posix(),job_file=job,commit=commit,submission_key=key,nonce=pending.nonce)
            except ZeusSubmissionError as error:
                if error.code in {
                    "submission_outcome_unknown",
                    "already_submitted",
                    "smoke_already_started",
                }:
                    self._previews.replace(token, replace(pending, terminal_error=error.code))
                raise
            if state.status!="submitted" or state.job_id is None or state.submitted_unix_s is None:
                self._previews.replace(token, replace(pending, terminal_error="submission_outcome_unknown"))
                raise ZeusSubmissionError("submission_outcome_unknown")
            if state.nonce!=pending.nonce:
                self._previews.replace(token, replace(pending, terminal_error="already_submitted"))
                raise ZeusSubmissionError("already_submitted")
            try: submitted_at=datetime.fromtimestamp(state.submitted_unix_s,tz=timezone.utc).isoformat()
            except (OverflowError,OSError,ValueError):
                self._previews.replace(token, replace(pending, terminal_error="submission_outcome_unknown"))
                raise ZeusSubmissionError("submission_outcome_unknown") from None
            result={"status":"submitted","campaign_id":pending.campaign_id,"stage":"smoke","job_id":state.job_id,"submitted_at":submitted_at,"later_stages_locked":True}
            # Publish the terminal result before releasing _confirm_lock so
            # concurrent retries cannot invoke the transport a second time.
            self._previews.replace(token, replace(pending, result=result))
            return dict(result)
