"""Independent deterministic DTOs returned by contract-test fake services."""
from __future__ import annotations

from copy import deepcopy

_PAYLOADS = {'campaign-detail': {'families': [],
                     'family': 'mot_2d',
                     'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                     'id': 'campaign-id',
                     'kind': 'mot_2d_s0_campaign',
                     'name': 'Campaign',
                     'next_plan': None,
                     'path': 'data/optimization/mot_2d/campaign-id',
                     'progress': [],
                     'remote_preparation': {'reason_code': None, 'status': 'ready'},
                     's0_values': [1.3],
                     'scheduler_status': 'unchecked',
                     'scientific_role': 'candidate-selection',
                     'stage': 'smoke',
                     'stage_semantics': 'prepared-workflow-stage',
                     'trust': 'trusted-current',
                     'warnings': []},
 'campaigns': {'campaigns': [], 'invalid_count': 0, 'total': 0},
 'confirmation-confirm': {'artifacts': {'created': 3, 'updated': 1},
                          'campaign_id': 'campaign-id',
                          'local_sync': {'status': 'not_synchronized'},
                          'simulation_started': False,
                          'stage': 'confirmation',
                          'status': 'confirmation_prepared',
                          'submitted_to_zeus': False},
 'confirmation-preview': {'artifacts': {'create': ['refined_candidates.json',
                                                   'confirmation/tasks.json',
                                                   'jobs/04_confirmation.pbs'],
                                        'update': ['campaign.json']},
                          'bounds': {'detuning_gamma': {'high': -0.1, 'low': -3.0},
                                     'magnet_radius_m': {'high': 0.06, 'low': 0.03}},
                          'campaign': {'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                       'id': 'campaign-id',
                                       'name': 'Campaign',
                                       's0_values': [1.3]},
                          'effects': {'overwrite_existing': False,
                                      'prepare_confirmation': True,
                                      'start_simulation': False,
                                      'submit_confirmation': False},
                          'expires_in_seconds': 300,
                          'from_stage': 'refine',
                          'job': {'array_throttle': 3,
                                  'cores_per_task': 200,
                                  'file': 'jobs/04_confirmation.pbs',
                                  'kind': 'array',
                                  'memory_per_task_bytes': 68719476736,
                                  'queue': 'zeus_combined_q',
                                  'task_count': 5,
                                  'walltime_seconds': 36000},
                          'local_sync': {'status': 'not_synchronized'},
                          'preview_token': 'confirmation-token',
                          'refinement': {'candidates': [{'detuning_gamma': -1.01,
                                                         'magnet_radius_m': 0.0401,
                                                         'mean_conditional_efficiency': 0.05,
                                                         'rank': 1,
                                                         's0': 1.3,
                                                         'source': 'refine/s0_1p300000/worker0/trials/trial_0001.json'},
                                                        {'detuning_gamma': -1.02,
                                                         'magnet_radius_m': 0.0402,
                                                         'mean_conditional_efficiency': 0.04,
                                                         'rank': 2,
                                                         's0': 1.3,
                                                         'source': 'refine/s0_1p300000/worker1/trials/trial_0002.json'},
                                                        {'detuning_gamma': -1.03,
                                                         'magnet_radius_m': 0.0403,
                                                         'mean_conditional_efficiency': 0.03,
                                                         'rank': 3,
                                                         's0': 1.3,
                                                         'source': 'refine/s0_1p300000/worker2/trials/trial_0003.json'},
                                                        {'detuning_gamma': -1.04,
                                                         'magnet_radius_m': 0.0404,
                                                         'mean_conditional_efficiency': 0.02,
                                                         'rank': 4,
                                                         's0': 1.3,
                                                         'source': 'refine/s0_1p300000/worker0/trials/trial_0004.json'},
                                                        {'detuning_gamma': -1.05,
                                                         'magnet_radius_m': 0.0405,
                                                         'mean_conditional_efficiency': 0.01,
                                                         'rank': 5,
                                                         's0': 1.3,
                                                         'source': 'refine/s0_1p300000/worker1/trials/trial_0005.json'}],
                                         'completed_trials': 30,
                                         'expected_trials': 30,
                                         'round_job_ids': ['301[].zeus-master',
                                                           '302[].zeus-master',
                                                           '303[].zeus-master',
                                                           '304[].zeus-master']},
                          'to_stage': 'confirmation'},
 'confirmation-status': {'campaign': {'id': 'campaign-id', 'name': 'Campaign', 'stage': 'refine'},
                         'chain': {'rounds': [{'depends_on_job_id': None,
                                               'job_id': '301[].zeus-master',
                                               'round': 1,
                                               'scheduler': {'counts': {'failed': 0,
                                                                        'held': 0,
                                                                        'queued': 0,
                                                                        'running': 0,
                                                                        'succeeded': 3},
                                                             'state': 'completed_success',
                                                             'task_count': 3}},
                                              {'depends_on_job_id': '301[].zeus-master',
                                               'job_id': '302[].zeus-master',
                                               'round': 2,
                                               'scheduler': {'counts': {'failed': 0,
                                                                        'held': 0,
                                                                        'queued': 0,
                                                                        'running': 0,
                                                                        'succeeded': 3},
                                                             'state': 'completed_success',
                                                             'task_count': 3}},
                                              {'depends_on_job_id': '302[].zeus-master',
                                               'job_id': '303[].zeus-master',
                                               'round': 3,
                                               'scheduler': {'counts': {'failed': 0,
                                                                        'held': 0,
                                                                        'queued': 0,
                                                                        'running': 0,
                                                                        'succeeded': 3},
                                                             'state': 'completed_success',
                                                             'task_count': 3}},
                                              {'depends_on_job_id': '303[].zeus-master',
                                               'job_id': '304[].zeus-master',
                                               'round': 4,
                                               'scheduler': {'counts': {'failed': 0,
                                                                        'held': 0,
                                                                        'queued': 0,
                                                                        'running': 0,
                                                                        'succeeded': 3},
                                                             'state': 'completed_success',
                                                             'task_count': 3}}],
                                   'status': 'ready_to_prepare_confirmation'},
                         'local_sync': {'status': 'not_synchronized'},
                         'next_action': 'review_confirmation_preparation',
                         'queried_at': '2026-10-08T00:00:00+00:00',
                         'source': 'zeus',
                         'validation': {'candidate_count': 5,
                                        'completed_trials': 30,
                                        'expected_trials': 30,
                                        'status': 'valid'}},
 'creation-confirm': {'campaign_id': 'campaign-id',
                      'path': 'data/optimization/mot_2d/campaign-id',
                      'stage': 'smoke',
                      'status': 'created',
                      'submitted_to_zeus': False},
 'creation-preview': {'duplicate': None,
                      'expires_in_seconds': 300,
                      'plan': {'files': ['campaign.json', 'jobs/01_smoke.pbs'],
                               'name': 'Campaign',
                               'path': 'data/optimization/mot_2d/campaign-id',
                               's0_values': [1.3],
                               'source_id': 'source',
                               'stage': 'smoke'},
                      'preview_token': 'creation-token',
                      'provenance': {'commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                     'input_count': 35},
                      'scientific_design': {}},
 'refinement-confirm': {'artifacts': {'created': 7, 'updated': 1},
                        'campaign_id': 'campaign-id',
                        'local_sync': {'status': 'not_synchronized'},
                        'simulation_started': False,
                        'stage': 'refine',
                        'status': 'refinement_prepared',
                        'submitted_to_zeus': False},
 'refinement-preview': {'artifacts': {'create': ['screening_candidates.json',
                                                 'refine/tasks.json',
                                                 'jobs/03_refine_round_01.pbs',
                                                 'jobs/03_refine_round_02.pbs',
                                                 'jobs/03_refine_round_03.pbs',
                                                 'jobs/03_refine_round_04.pbs',
                                                 'jobs/03_submit_refinement_chain.sh'],
                                      'update': ['campaign.json']},
                        'bounds': {'detuning_gamma': {'high': -0.1, 'low': -3.0},
                                   'magnet_radius_m': {'high': 0.06, 'low': 0.03}},
                        'campaign': {'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                     'id': 'campaign-id',
                                     'name': 'Campaign',
                                     's0_values': [1.3]},
                        'effects': {'overwrite_existing': False,
                                    'prepare_refinement': True,
                                    'start_simulation': False,
                                    'submit_refinement': False},
                        'expires_in_seconds': 300,
                        'from_stage': 'screen',
                        'local_sync': {'status': 'not_synchronized'},
                        'preview_token': 'refine-token',
                        'screening': {'candidates': [{'detuning_gamma': -1.0,
                                                      'magnet_radius_m': 0.04,
                                                      'mean_conditional_efficiency': 0.03,
                                                      'rank': 1,
                                                      's0': 1.3,
                                                      'source': 'screen/s0_1p300000/worker0/trials/trial_0001.json'},
                                                     {'detuning_gamma': -1.1,
                                                      'magnet_radius_m': 0.041,
                                                      'mean_conditional_efficiency': 0.02,
                                                      'rank': 2,
                                                      's0': 1.3,
                                                      'source': 'screen/s0_1p300000/worker1/trials/trial_0002.json'},
                                                     {'detuning_gamma': -1.2,
                                                      'magnet_radius_m': 0.042,
                                                      'mean_conditional_efficiency': 0.01,
                                                      'rank': 3,
                                                      's0': 1.3,
                                                      'source': 'screen/s0_1p300000/worker2/trials/trial_0003.json'}],
                                      'completed_trials': 51,
                                      'expected_trials': 51,
                                      'job_id': '200[].zeus-master'},
                        'to_stage': 'refine'},
 'refinement-submit-confirm': {'campaign_id': 'campaign-id',
                               'chain': {'rounds': [{'depends_on_job_id': None,
                                                     'job_id': '301[].zeus-master',
                                                     'round': 1},
                                                    {'depends_on_job_id': '301[].zeus-master',
                                                     'job_id': '302[].zeus-master',
                                                     'round': 2},
                                                    {'depends_on_job_id': '302[].zeus-master',
                                                     'job_id': '303[].zeus-master',
                                                     'round': 3},
                                                    {'depends_on_job_id': '303[].zeus-master',
                                                     'job_id': '304[].zeus-master',
                                                     'round': 4}],
                                         'status': 'submitted'},
                               'local_sync': {'status': 'not_synchronized'},
                               'stage': 'refine',
                               'status': 'submitted',
                               'submitted_at': '2026-10-08T00:00:00+00:00'},
 'refinement-submit-preview': {'campaign': {'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                            'id': 'campaign-id',
                                            'name': 'Campaign',
                                            's0_values': [1.3]},
                               'chain': {'dependency': 'afterok',
                                         'rounds': [{'array_throttle': 3,
                                                     'cores_per_task': 200,
                                                     'cumulative_target': 3,
                                                     'depends_on': None,
                                                     'file': 'jobs/03_refine_round_01.pbs',
                                                     'kind': 'array',
                                                     'memory_per_task_bytes': 68719476736,
                                                     'queue': 'zeus_combined_q',
                                                     'round': 1,
                                                     'task_count': 3,
                                                     'walltime_seconds': 72000},
                                                    {'array_throttle': 3,
                                                     'cores_per_task': 200,
                                                     'cumulative_target': 6,
                                                     'depends_on': 1,
                                                     'file': 'jobs/03_refine_round_02.pbs',
                                                     'kind': 'array',
                                                     'memory_per_task_bytes': 68719476736,
                                                     'queue': 'zeus_combined_q',
                                                     'round': 2,
                                                     'task_count': 3,
                                                     'walltime_seconds': 72000},
                                                    {'array_throttle': 3,
                                                     'cores_per_task': 200,
                                                     'cumulative_target': 9,
                                                     'depends_on': 2,
                                                     'file': 'jobs/03_refine_round_03.pbs',
                                                     'kind': 'array',
                                                     'memory_per_task_bytes': 68719476736,
                                                     'queue': 'zeus_combined_q',
                                                     'round': 3,
                                                     'task_count': 3,
                                                     'walltime_seconds': 72000},
                                                    {'array_throttle': 3,
                                                     'cores_per_task': 200,
                                                     'cumulative_target': 10,
                                                     'depends_on': 3,
                                                     'file': 'jobs/03_refine_round_04.pbs',
                                                     'kind': 'array',
                                                     'memory_per_task_bytes': 68719476736,
                                                     'queue': 'zeus_combined_q',
                                                     'round': 4,
                                                     'task_count': 3,
                                                     'walltime_seconds': 72000}]},
                               'effects': {'modify_files': False,
                                           'start_simulation': True,
                                           'submit_later_stages': False,
                                           'submit_refinement_chain': True},
                               'expires_in_seconds': 300,
                               'local_sync': {'status': 'not_synchronized'},
                               'preview_token': 'chain-token',
                               'remote': {'branch': 'main',
                                          'commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                          'dirty': False,
                                          'host': 'zeus.technion.ac.il',
                                          'project_directory': '/home/tal.noa/ytterbium_lab_simulation_new'},
                               'stage': {'id': 'refine', 'label': 'Refinement'}},
 'refinement-submit-status': {'campaign': {'id': 'campaign-id',
                                           'name': 'Campaign',
                                           'stage': 'refine'},
                              'chain': {'dependency': 'afterok',
                                        'rounds': [{'depends_on_job_id': None,
                                                    'job_id': None,
                                                    'round': 1,
                                                    'state': 'not_submitted'},
                                                   {'depends_on_job_id': None,
                                                    'job_id': None,
                                                    'round': 2,
                                                    'state': 'not_submitted'},
                                                   {'depends_on_job_id': None,
                                                    'job_id': None,
                                                    'round': 3,
                                                    'state': 'not_submitted'},
                                                   {'depends_on_job_id': None,
                                                    'job_id': None,
                                                    'round': 4,
                                                    'state': 'not_submitted'}],
                                        'status': 'not_submitted'},
                              'local_sync': {'status': 'not_synchronized'},
                              'next_action': 'review_submission',
                              'queried_at': '2026-10-08T00:00:00+00:00',
                              'source': 'zeus'},
 'screen-status': {'campaign': {'id': 'campaign-id', 'name': 'Campaign', 'stage': 'screen'},
                   'lifecycle': 'ready_to_prepare_refinement',
                   'next_action': 'review_refinement_preparation',
                   'queried_at': '2026-10-08T00:00:00+00:00',
                   'scheduler': {'counts': {'failed': 0,
                                            'held': 0,
                                            'queued': 0,
                                            'running': 0,
                                            'succeeded': 3},
                                 'exit_status': 0,
                                 'raw_state': 'F',
                                 'state': 'completed_success',
                                 'task_count': 3},
                   'source': 'zeus',
                   'submission': {'job_id': '200[].zeus-master'},
                   'validation': {'candidate_count': 3,
                                  'completed_trials': 51,
                                  'expected_trials': 51,
                                  'status': 'valid'}},
 'screen-submit-confirm': {'campaign_id': 'campaign-id',
                           'job_id': '200[].zeus-master',
                           'later_stages_locked': True,
                           'stage': 'screen',
                           'status': 'submitted',
                           'submitted_at': '2026-10-08T00:00:00+00:00'},
 'screen-submit-preview': {'campaign': {'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                        'id': 'campaign-id',
                                        'name': 'Campaign',
                                        's0_values': [1.3]},
                           'effects': {'modify_files': False,
                                       'submit_later_stages': False,
                                       'submit_screening': True},
                           'expires_in_seconds': 300,
                           'inputs': {'status': 'ready', 'verified_count': 72},
                           'job': {'array_throttle': 3,
                                   'cores_per_task': 200,
                                   'file': 'jobs/02_screen.pbs',
                                   'kind': 'array',
                                   'memory_per_task_bytes': 68719476736,
                                   'queue': 'zeus_combined_q',
                                   'task_count': 3,
                                   'walltime_seconds': 86400},
                           'later_stages_locked': True,
                           'preview_token': 'screen-submit-token',
                           'remote': {'branch': 'main',
                                      'commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                      'dirty': False,
                                      'host': 'zeus.technion.ac.il',
                                      'project_directory': '/home/tal.noa/ytterbium_lab_simulation_new'},
                           'smoke': {'job_id': '100.zeus-master',
                                     'point_count': 1,
                                     'status': 'validated'},
                           'stage': {'id': 'screen',
                                     'label': 'Screening',
                                     'purpose': 'Broad search.'}},
 'screening-confirm': {'artifacts': {'created': 2, 'updated': 1},
                       'campaign_id': 'campaign-id',
                       'local_sync': {'status': 'not_synchronized'},
                       'simulation_started': False,
                       'stage': 'screen',
                       'status': 'screening_prepared',
                       'submitted_to_zeus': False},
 'screening-preview': {'artifacts': {'create': ['screen/tasks.json', 'jobs/02_screen.pbs'],
                                     'update': ['campaign.json']},
                       'campaign': {'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                    'id': 'campaign-id',
                                    'name': 'Campaign'},
                       'effects': {'overwrite_existing': False,
                                   'prepare_screening': True,
                                   'start_simulation': False,
                                   'submit_screening': False},
                       'expires_in_seconds': 300,
                       'from_stage': 'smoke',
                       'local_sync': {'status': 'not_synchronized'},
                       'preview_token': 'screen-token',
                       'smoke': {'artifact_count': 3,
                                 'job_id': '100.zeus-master',
                                 'points': [{'captured': 0,
                                             'efficiency': 0.0,
                                             'input': 2,
                                             's0': 1.3}]},
                       'to_stage': 'screen'},
 'smoke-status': {'campaign': {'id': 'campaign-id', 'name': 'Campaign', 'stage': 'smoke'},
                  'lifecycle': 'ready_to_prepare_screen',
                  'next_action': 'review_screening_preparation',
                  'queried_at': '2026-10-08T00:00:00+00:00',
                  'scheduler': {'exit_status': 0, 'raw_state': 'F', 'state': 'completed_success'},
                  'source': 'zeus',
                  'submission': {'job_id': '100.zeus-master'},
                  'validation': {'artifact_count': 3,
                                 'points': [{'captured': 0,
                                             'efficiency': 0.0,
                                             'input': 2,
                                             's0': 1.3}],
                                 'status': 'valid'}},
 'smoke-submit-confirm': {'campaign_id': 'campaign-id',
                          'job_id': '100.zeus-master',
                          'later_stages_locked': True,
                          'stage': 'smoke',
                          'status': 'submitted',
                          'submitted_at': '2026-10-08T00:00:00+00:00'},
 'smoke-submit-preview': {'campaign': {'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                       'id': 'campaign-id',
                                       'name': 'Campaign',
                                       'path': 'data/optimization/mot_2d/campaign-id',
                                       's0_values': [1.3]},
                          'effects': {'modify_files': False,
                                      'submit_later_stages': False,
                                      'submit_smoke': True},
                          'expires_in_seconds': 300,
                          'inputs': {'status': 'ready', 'verified_count': 72},
                          'job': {'cores_per_task': 1,
                                  'file': 'jobs/01_smoke.pbs',
                                  'kind': 'job',
                                  'memory_per_task_bytes': 68719476736,
                                  'queue': 'zeus_combined_q',
                                  'task_count': 1,
                                  'walltime_seconds': 1200},
                          'later_stages_locked': True,
                          'preview_token': 'smoke-token',
                          'remote': {'branch': 'main',
                                     'commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                     'dirty': False,
                                     'host': 'zeus.technion.ac.il',
                                     'project_directory': '/home/tal.noa/ytterbium_lab_simulation_new'},
                          'stage': {'id': 'smoke',
                                    'label': 'Smoke check',
                                    'purpose': 'Validate setup.'}},
 'sources': {'invalid_count': 0, 'sources': [], 'total': 0},
 'transfer-confirm': {'bytes_transferred': 100,
                      'campaign_id': 'campaign-id',
                      'destination': '/home/tal.noa/ytterbium_lab_simulation_new/data/optimization/mot_2d/campaign-id',
                      'reused_identical_count': 0,
                      'simulation_started': False,
                      'status': 'prepared',
                      'submitted_to_zeus': False,
                      'transferred_count': 72},
 'transfer-preview': {'artifacts': {'ensemble_count': 35,
                                    'identical_count': 0,
                                    'missing_bytes': 100,
                                    'missing_count': 72,
                                    'total_bytes': 100,
                                    'total_count': 72},
                      'campaign': {'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                                   'id': 'campaign-id',
                                   'name': 'Campaign',
                                   'path': 'data/optimization/mot_2d/campaign-id'},
                      'destination': {'campaign_directory': '/home/tal.noa/ytterbium_lab_simulation_new/data/optimization/mot_2d/campaign-id',
                                      'host': 'zeus.technion.ac.il',
                                      'project_directory': '/home/tal.noa/ytterbium_lab_simulation_new'},
                      'effects': {'copy_missing_only': True,
                                  'overwrite_existing': False,
                                  'run_simulation': False,
                                  'submit_jobs': False},
                      'expires_in_seconds': 300,
                      'preview_token': 'transfer-token'},
 'workflows': [],
 'zeus-snapshot': {'connection_status': 'connected',
                   'profile': {'authentication': 'ssh-key-or-agent',
                               'host': 'zeus.technion.ac.il',
                               'project_directory': '/home/tal.noa/ytterbium_lab_simulation_new',
                               'username': 'tal.noa'},
                   'remote': {'branch': 'main',
                              'dirty': False,
                              'git_commit': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                              'project_directory': '/home/tal.noa/ytterbium_lab_simulation_new'},
                   'scheduler': {'jobs': [],
                                 'queried_at': '2026-10-08T00:00:00+00:00',
                                 'status': 'available'}}}


def fake_service_payloads() -> dict[str, object]:
    """Return fresh full public DTOs without consulting contract snapshots."""
    return deepcopy(_PAYLOADS)


