import { getData, postData } from "../http/envelope";
import { parseCampaign, parsePreview, type Campaign, type CreationPreview, type CreationResult, type ZeemanSource } from "../schema/domain";
import { finiteNonnegative, text } from "../schema/common";
import { MOT_2D_SPECIFICATION_V1 } from "../../generated/mot2dSpec.v1";
export type { Campaign, CreationPreview, CreationResult, ZeemanSource } from "../schema/domain";
export const campaignApi={async list(){const data=await getData("/api/v1/campaigns") as Record<string,unknown>;if(!data||!Array.isArray(data.campaigns)||!finiteNonnegative(data.invalid_count)||!finiteNonnegative(data.total)||data.total!==data.campaigns.length)throw new Error("Invalid campaign list response.");return{...data,campaigns:data.campaigns.map(parseCampaign)} as {campaigns:Campaign[];invalid_count:number;total:number};},async get(id:string){return parseCampaign(await getData(`/api/v1/campaigns/${encodeURIComponent(id)}`));}};
export type CampaignApi=typeof campaignApi;
export const creationApi={async sources():Promise<ZeemanSource[]>{const data=await getData("/api/v1/campaigns/2d/sources") as Record<string,unknown>;if(!data||!Array.isArray(data.sources)||data.total!==data.sources.length)throw new Error("Invalid Zeeman source response.");return data.sources.map((value)=>{if(!value||typeof value!=="object")throw new Error("Invalid Zeeman source response.");const row=value as Record<string,unknown>;if(!text(row.id)||!text(row.path)||!text(row.profile)||row.ensemble_count!==MOT_2D_SPECIFICATION_V1.design.ensemble_count||!finiteNonnegative(row.minimum_survivors)||!finiteNonnegative(row.maximum_survivors)||!text(row.fingerprint))throw new Error("Invalid Zeeman source response.");return row as unknown as ZeemanSource;});},async session():Promise<string>{const data=await getData("/api/v1/session") as Record<string,unknown>;if(!data||!text(data.csrf_token))throw new Error("Invalid local creation session.");return data.csrf_token;},async preview(input:{name:string;slug:string;source_id:string;s0_values:number[]},csrf:string):Promise<CreationPreview>{return parsePreview(await postData("/api/v1/campaigns/2d/preview",input,csrf));},async confirm(preview_token:string,csrf:string):Promise<CreationResult>{const row=await postData("/api/v1/campaigns/2d/confirm",{preview_token},csrf);if(row.status!=="created"||!text(row.campaign_id)||!text(row.path)||row.stage!=="smoke"||row.submitted_to_zeus!==false)throw new Error("Invalid campaign creation response.");return row as unknown as CreationResult;}};
export type CreationApi=typeof creationApi;
