import { postData } from "../http/envelope";
import { ScreeningLifecycleApiError, ScreeningSubmissionApiError } from "../http/errors";
import { parseRefinementPreview, parseRefinementResult, parseScreeningLifecycle, parseScreeningSubmissionPreview, parseScreeningSubmissionResult, type RefinementPreview, type RefinementResult, type ScreeningLifecycle, type ScreeningSubmissionPreview, type ScreeningSubmissionResult, type ZeusSnapshot } from "../schema/domain";
import { creationApi } from "./campaign";
export { ScreeningLifecycleApiError, ScreeningSubmissionApiError } from "../http/errors";
export { type RefinementPreview, type RefinementResult, type ScreeningLifecycle, type ScreeningSubmissionPreview, type ScreeningSubmissionResult } from "../schema/domain";
type Session=()=>Promise<string>; type Context={campaignId:string;csrf:string};
export function createScreeningSubmissionApi(session:Session){const contexts=new Map<string,Context>();return{
 async preview(campaign_id:string,profile:ZeusSnapshot["profile"]):Promise<ScreeningSubmissionPreview>{const csrf=await session();const value=parseScreeningSubmissionPreview(await postData("/api/v1/zeus/submissions/screening/preview",{campaign_id,username:profile.username,project_directory:profile.project_directory},csrf,e=>new ScreeningSubmissionApiError(e.code,e.message)));if(value.campaign.id!==campaign_id||value.remote.project_directory!==profile.project_directory)throw new Error("Screening submission preview did not match the selected campaign and profile.");contexts.set(value.preview_token,{campaignId:campaign_id,csrf});return value;},
 async confirm(preview_token:string):Promise<ScreeningSubmissionResult>{const context=contexts.get(preview_token);if(!context)throw new Error("The Screening submission preview is no longer active.");contexts.delete(preview_token);try{const value=parseScreeningSubmissionResult(await postData("/api/v1/zeus/submissions/screening/confirm",{preview_token},context.csrf,e=>new ScreeningSubmissionApiError(e.code,e.message)));if(value.campaign_id!==context.campaignId)throw new Error("Screening submission result did not match the reviewed campaign.");return value;}catch(error){if(error instanceof ScreeningSubmissionApiError)throw error;throw new ScreeningSubmissionApiError("screening_submission_outcome_unknown","The submission result could not be verified. Do not submit again; inspect Zeus jobs.");}},reset(){contexts.clear();}};}
export function createScreeningLifecycleApi(session:Session){const contexts=new Map<string,Context>();return{
 async status(campaign_id:string,profile:ZeusSnapshot["profile"]):Promise<ScreeningLifecycle>{const csrf=await session();const value=parseScreeningLifecycle(await postData("/api/v1/zeus/screen/status",{campaign_id,username:profile.username,project_directory:profile.project_directory},csrf,e=>new ScreeningLifecycleApiError(e.code,e.message)));if(value.campaign.id!==campaign_id)throw new Error("Screening lifecycle did not match the selected campaign.");return value;},
 async preview(campaign_id:string,profile:ZeusSnapshot["profile"]):Promise<RefinementPreview>{const csrf=await session();const value=parseRefinementPreview(await postData("/api/v1/zeus/refinement/preview",{campaign_id,username:profile.username,project_directory:profile.project_directory},csrf,e=>new ScreeningLifecycleApiError(e.code,e.message)));if(value.campaign.id!==campaign_id)throw new Error("Refinement preparation preview did not match the selected campaign.");contexts.set(value.preview_token,{campaignId:campaign_id,csrf});return value;},
 async confirm(preview_token:string):Promise<RefinementResult>{const context=contexts.get(preview_token);if(!context)throw new Error("The Refinement preparation preview is no longer active.");contexts.delete(preview_token);const value=parseRefinementResult(await postData("/api/v1/zeus/refinement/confirm",{preview_token},context.csrf,e=>new ScreeningLifecycleApiError(e.code,e.message)));if(value.campaign_id!==context.campaignId)throw new Error("Refinement preparation result did not match the reviewed campaign.");return value;},reset(){contexts.clear();}};}
export type ScreeningSubmissionApi=Pick<ReturnType<typeof createScreeningSubmissionApi>,"preview"|"confirm">;export type ScreeningLifecycleApi=Pick<ReturnType<typeof createScreeningLifecycleApi>,"status"|"preview"|"confirm">;
export const screeningSubmissionApi=createScreeningSubmissionApi(()=>creationApi.session());export const screeningLifecycleApi=createScreeningLifecycleApi(()=>creationApi.session());
