import { postData } from "../http/envelope";
import { creationApi } from "./campaign";
import { ZeusApiError } from "../http/errors";
import { parseTransferPreview,parseTransferResult,parseZeusSnapshot,type ZeusJob,type ZeusSnapshot,type ZeusTransferPreview,type ZeusTransferResult } from "../schema/domain";
export { ZeusApiError } from "../http/errors";
export {type ZeusJob,type ZeusSnapshot,type ZeusTransferPreview,type ZeusTransferResult} from "../schema/domain";
export function createZeusApi(session:()=>Promise<string>){return{async snapshot(username:string,project_directory:string):Promise<ZeusSnapshot>{const csrf=await session();const snapshot=parseZeusSnapshot(await postData("/api/v1/zeus/snapshot",{username,project_directory},csrf,(error)=>new ZeusApiError(error.code,error.message)));if(snapshot.profile.username!==username||snapshot.profile.project_directory!==project_directory||snapshot.remote.project_directory!==project_directory)throw new Error("Zeus snapshot did not match the requested profile.");return snapshot;}};}
export function createTransferApi(session:()=>Promise<string>){const contexts=new Map<string,{campaignId:string;destination:string;csrf:string}>();return{async preview(campaign_id:string,profile:ZeusSnapshot["profile"]):Promise<ZeusTransferPreview>{const csrf=await session();const preview=parseTransferPreview(await postData("/api/v1/zeus/transfers/preview",{campaign_id,username:profile.username,project_directory:profile.project_directory},csrf));if(preview.campaign.id!==campaign_id||preview.destination.project_directory!==profile.project_directory)throw new Error("Zeus preparation preview did not match the requested campaign and profile.");contexts.set(preview.preview_token,{campaignId:campaign_id,destination:preview.destination.campaign_directory,csrf});return preview;},async confirm(preview_token:string):Promise<ZeusTransferResult>{const context=contexts.get(preview_token);if(!context)throw new Error("The Zeus preparation preview is no longer active.");contexts.delete(preview_token);const result=parseTransferResult(await postData("/api/v1/zeus/transfers/confirm",{preview_token},context.csrf));if(result.campaign_id!==context.campaignId||result.destination!==context.destination)throw new Error("Zeus preparation result did not match the reviewed plan.");return result;},reset(){contexts.clear();}};}
export type ZeusApi=ReturnType<typeof createZeusApi>;export type TransferApi=Pick<ReturnType<typeof createTransferApi>,"preview"|"confirm">;
export const zeusApi=createZeusApi(()=>creationApi.session());export const transferApi=createTransferApi(()=>creationApi.session());
