"""Generate frontend-only error semantics from the frozen backend catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tests/contracts/v1/workflow_api_error_catalog.json"
OUTPUT = ROOT / "ui/src/generated/errorCatalog.v1.ts"

FRESH_REVIEW = {"confirmation_expired", "confirmation_invalid", "local_files_changed"}
ALREADY_PREPARED = {
    "screening_already_prepared",
    "refinement_already_prepared",
    "confirmation_already_prepared",
}
OUTCOME_UNKNOWN = {
    "submission_outcome_unknown",
    "screening_submission_outcome_unknown",
    "refinement_submission_outcome_unknown",
    "transition_outcome_unknown",
}
MANUAL = {
    "already_submitted",
    "smoke_already_started",
    "submission_record_invalid",
    "transition_conflict",
    "screening_submission_record_invalid",
    "screening_already_submitted",
    "screening_already_started",
    "refinement_chain_partially_submitted",
    "refinement_chain_already_submitted",
    "refinement_already_started",
}


def semantic(code: str) -> str:
    if code in FRESH_REVIEW:
        return "fresh_review"
    if code in ALREADY_PREPARED:
        return "already_prepared"
    if code in OUTCOME_UNKNOWN:
        return "outcome_unknown"
    if code in MANUAL:
        return "manual_verification"
    return "other"


def render() -> str:
    payload = json.loads(SOURCE.read_text())
    rows = sorted(
        {
            (row["domain"], row["code"], semantic(row["code"]))
            for row in payload["cases"]
            if row["case"] != "<fallback>"
        }
    )
    encoded = json.dumps(
        [{"domain": domain, "code": code, "semantic": meaning} for domain, code, meaning in rows],
        indent=2,
    )
    return (
        "// Generated by scripts/generate_ui_error_catalog.py; do not edit.\n"
        "export const serverErrorCatalog = " + encoded + " as const;\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not args.output.exists() or args.output.read_text() != content:
            parser.exit(1, f"frontend error catalog is out of date: {args.output}\n")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)


if __name__ == "__main__":
    main()
